Add basic tests for regression
vsecades/AbuseIpDb pull request #7
Opened 2019-12-26 08:35 UTC by Eorhim

I should have added them right at the start. Unfortunately I introduced an API change with my refactoring. Still I think, it is much cleaner than the print statements.

These tests will be the safety net for all future changes. They uncover that `check_cidr` and `report_ip` can create malformed URL. As Abuse IP DB set the sunset date for APIv2 to 2020-02-01, it doesn't make sense to fix that.

2019-12-26 15:20 UTC, vsecades requested changes
Please leave as it was.  This was a boilerplate item that we can use at a later date.

2019-12-26 15:21 UTC, vsecades approved these changes

2019-12-26 15:22 UTC, vsecades approved these changes

2019-12-26 15:23 UTC, vsecades commented on tests/test_legacy.py
> +            abuseipdb.check_ip(ip='192.0.2.123')
Who does this IP belong to?

2019-12-26 15:23 UTC, vsecades approved these changes
Just a quick question out of curiosity.

2019-12-26 15:25 UTC, vsecades approved these changes

2019-12-26 15:27 UTC, vsecades requested changes
Please move the IP address off to either a static or shared variable.  This might be confusing for maintenance later on.

2019-12-26 15:27 UTC, vsecades approved these changes

2019-12-26 15:28 UTC, vsecades commented on tests/test_legacy.py
> +            abuseipdb.report_ip(ip='192.0.2.123')
Same as before please move any mention of the ip off to a shared or static variable.

2019-12-26 15:29 UTC, vsecades requested changes
Added a comment with a change request on the IP as before.  Thanks again for your contributions.

2019-12-26 16:30 UTC, Eorhim reviewed
Hello Valentin,
thank you for your quick reviews. With the Christmas holidays I was expecting a much longer waiting time. I'm using my free time to advance some of my private projects and talking with Abuse IP DB in a clean way is a prerequisite for that.
I hope my working style (small commits and pull requests) doesn't annoy you too much. This one is the real starting point for future changes. The tests could still use some polishing, but as APIv1 will only work for a month, I will spare the effort to extend them further.
I'm really curious about your opinion on my next change. It introduces a new usage in parallel to the existing one to set the stage for the APIv2. It also makes the package work with Python 3.
I wish you a merry Christmas!
Eorhim

2019-12-26 16:30 UTC, Eorhim commented on tests/test_legacy.py
> +            abuseipdb.check_ip(ip='192.0.2.123')
This is an IP range set apart for documentation and testing as of RFC5737: https://tools.ietf.org/html/rfc5737

2019-12-26 22:05 UTC, vsecades approved these changes

2019-12-27 17:17 UTC, vsecades commented on tests/test_legacy.py
> +            abuseipdb.check_ip(ip='192.0.2.123')
Cool. Thanks for the info.

2019-12-27 17:19 UTC, vsecades commented
@Eorhim thanks for the contributions.  I got a response from AbuseIPDB that they want to publish this alongside their service, so would be good to get this wrapped up in the next week or so, if you have the time.  

I'll take a look at the changes for V2 to see how to move forward.

2019-12-27 17:54 UTC, Eorhim commented
Hello Valentin,
is there still something missing from my side? Did I overlook some requested change?
My fork is now in a state, where it fits my needs. I'm also satisfied with the test coverage and structure. Feel free to pull the changes.
If you do so, either merge `develop` directly or merge the branches `develop-add-tests`, `develop-add-new-class-interface` and `develop-add-apiv2` in that order. They're based on each other.
I'm happy to hear suggestions for improvement. If I don't hear from you, I'll move on to the next part in my project.
As I'm offline for the next few days, I wish you a habby new year!
Eorhim

2019-12-27 18:07 UTC, vsecades commented
Hi Sebastian,

If you have the chance to talk, that would be great.  Reach out to me via
Skype at vsecades, or we can find some other means of communication.

 If you can make a pull request with the latest changes, that would be
great as well.

Thanks again for your help.

Cheers,
Valentin

On Fri, Dec 27, 2019, 11:54 AM Sebastian Bonhag <notifications@github.com>
wrote:

> Hello Valentin,
> is there still something missing from my side? Did I overlook some
> requested change?
> My fork is now in a state, where it fits my needs. I'm also satisfied with
> the test coverage and structure. Feel free to pull the changes.
> If you do so, either merge develop directly or merge the branches
> develop-add-tests, develop-add-new-class-interface and develop-add-apiv2
> in that order. They're based on each other.
> I'm happy to hear suggestions for improvement. If I don't hear from you,
> I'll move on to the next part in my project.
> As I'm offline for the next few days, I wish you a habby new year!
> Eorhim
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/vsecades/AbuseIpDb/pull/7?email_source=notifications&email_token=AAGTDCBWOR2TTBHUT5G2Y53Q2Y6L7A5CNFSM4J7JO4V2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHXRG2Y#issuecomment-569316203>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAGTDCHPQVSBNWRNTRYEXVDQ2Y6L7ANCNFSM4J7JO4VQ>
> .
>

2019-12-27 18:09 UTC, Eorhim commented
@vsecades As I wrote in the `README.md`, only the functionality for `bulk_upload` is missing.
And I forgot one thing: decoding the JSON and the tests for that. I'm unsure, if I should leave it at that or create a specific response class ...

2019-12-27 20:35 UTC, vsecades commented
> Please leave as it was. This was a boilerplate item that we can use at a later date.

Hi @Eorhim this is one of the pending items :-)

2019-12-27 21:29 UTC, merged